name: Test and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Gradle
        run: './gradlew test'

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -PJorisgUsername=${{ secrets.JORISG_REPO_USERNAME }} -PJorisgPassword ${{ secrets.JORISG_REPO_PASSWORD }}